language: node_js
node_js:
- stable
addons:
  postgresql: "9.7"
#  apt:
#    packages:
#    - postgresql-10
#    - postgresql-client-10
# env:
#  global:
#  - PGPORT=5433
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm run coverage